"""init tables

Revision ID: de855763e0cd
Revises: 
Create Date: 2025-09-26 08:02:10.886626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de855763e0cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('clustering_dataset_h',
    sa.Column('clustering_dataset_h_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clustering_dataset_h_id')
    )
    op.create_index(op.f('ix_clustering_dataset_h_clustering_dataset_h_id'), 'clustering_dataset_h', ['clustering_dataset_h_id'], unique=False)
    op.create_table('clustering_dataset_d',
    sa.Column('clustering_dataset_d_id', sa.Integer(), nullable=False),
    sa.Column('clustering_dataset_h_id', sa.Integer(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('kabupaten_kota', sa.String(length=100), nullable=False),
    sa.Column('angka_harapan_hidup', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('persentase_penduduk_miskin', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('index_kedalaman_kemiskinan', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('index_keparahan_kemiskinan', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('rata_rata_lama_sekolah', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clustering_dataset_h_id'], ['clustering_dataset_h.clustering_dataset_h_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clustering_dataset_d_id')
    )
    op.create_index(op.f('ix_clustering_dataset_d_clustering_dataset_d_id'), 'clustering_dataset_d', ['clustering_dataset_d_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clustering_dataset_d_clustering_dataset_d_id'), table_name='clustering_dataset_d')
    op.drop_table('clustering_dataset_d')
    op.drop_index(op.f('ix_clustering_dataset_h_clustering_dataset_h_id'), table_name='clustering_dataset_h')
    op.drop_table('clustering_dataset_h')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
