"""add activity log

Revision ID: ed24f5001c7f
Revises: 0d46d2568a3e
Create Date: 2025-10-17 21:09:13.681295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed24f5001c7f'
down_revision: Union[str, Sequence[str], None] = '0d46d2568a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metode_clustering', sa.String(length=50), nullable=False),
    sa.Column('fitur_digunakan', sa.JSON(), nullable=False),
    sa.Column('tahun_awal', sa.Integer(), nullable=False),
    sa.Column('tahun_akhir', sa.Integer(), nullable=False),
    sa.Column('jumlah_cluster', sa.Integer(), nullable=True),
    sa.Column('metrik_jarak', sa.String(length=50), nullable=False),
    sa.Column('silhouette', sa.String(length=50), nullable=True),
    sa.Column('dbi', sa.String(length=50), nullable=True),
    sa.Column('waktu_komputasi', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_id'), 'activity_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_log_id'), table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
