"""add ahh_l and ahh_p columns

Revision ID: effc5290230f
Revises: de855763e0cd
Create Date: 2025-10-17 19:36:14.135247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effc5290230f'
down_revision: Union[str, Sequence[str], None] = 'de855763e0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clustering_dataset_d', sa.Column('angka_harapan_hidup_l', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('clustering_dataset_d', sa.Column('angka_harapan_hidup_p', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.drop_column('clustering_dataset_d', 'angka_harapan_hidup')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clustering_dataset_d', sa.Column('angka_harapan_hidup', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_column('clustering_dataset_d', 'angka_harapan_hidup_p')
    op.drop_column('clustering_dataset_d', 'angka_harapan_hidup_l')
    # ### end Alembic commands ###
