[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[theme]
base = "dark"
primaryColor = "#4da6ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[client]
showErrorDetails = true
toolbarMode = "minimal"
