COOKIE_PASSWORD = "wAJKsLUzI5_WxnW2WAF9TtgjFgMLKGFoHNga0Oy7gLm4-AaBPa9NpgOuXQrQdymU"
DB_URL = "postgresql://neondb_owner:npg_tZOyNdj20Crq@ep-rough-mode-a1dhgduq-pooler.ap-southeast-1.aws.neon.tech/clustering_wilayah?sslmode=require"